server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tomato_oauth?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    username: tomato
    password: tomato
