### 登录
POST http://localhost:8001/sys/user/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "captchaCode": "123456",
  "captchaUuid": "123456",
  "loginDevice": 1

}
> {% client.global.set("access_token", response.body.data.access_token);client.global.set("refresh_token", response.body.data.refresh_token); %}

### hello world
GET http://localhost:8001
Authorization: Bearer {{access_token}}

### 退出
GET http://localhost:8001/sys/user/logout
Authorization: Bearer {{access_token}}

### 刷新token
POST http://localhost:8001/token/refresh-token
Authorization: Bearer {{refresh_token}}


### 更新禁用/启用状态
GET http://localhost:8080/sys/user/update/disabled/100

### 创建用户
POST http://localhost:8080/sys/user/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "actualName": "李志福",
  "loginName": "lizhifu",
  "gender": 1,
  "departmentId": 1,
  "disabledFlag": 1,
  "phone": "18810869700"
}