# 标准的 Jenkins Docker 部署文件,利用官方镜像来启动 Jenkins 服务
# version:指定 Docker Compose版本,这里是3.8
version: "3.8"
# services:服务定义部分。其下面定义了一个名为jenkins的服务
services:
  jenkins:
    #  image:指定服务使用的镜像,这里是jenkinsci/blueocean。这是一个官方的Jenkins镜像。
    image: jenkinsci/blueocean
    #  container_name:容器名称,此处设置为jenkins
    container_name: jenkins
    # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    restart: unless-stopped
    #  hostname:主机名设置为jenkins
    hostname: jenkins
    #  privileged:赋予该容器特权模式。Jenkins需要 Docker 命令执行权限,需要特权模式
    privileged: true
    # user:指定容器内进程运行用户为root，# 使用root权限运行容器【docker中通过`-u root`命令】
    user: root
    # environment:环境变量部分
    environment:
      # 设置时区为上海时区
      TZ: "Asia/Shanghai"
    # volumes:数据卷挂载路径设置,将本机目录映射到容器目录 (下面映射可在容器中执行宿主机docker命令)
    # Jenkins 数据会保存到挂载的 /var/jenkins_home 目录,并可以使用本地的 Maven 缓存。
    #
    volumes:
      - /usr/local/docker-volumes/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local:/home
      - /usr/local/maven-repository:/root/.m2
    # ports:端口映射,将 8080 和 50000 端口映射到宿主机
    ports:
      - "8888:8080"
      - "51000:50000"