package com.tomato.mybatis.generator.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class NoticeRuleExample {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	public NoticeRuleExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	protected abstract static class GeneratedCriteria {

		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andRuleCodeIsNull() {
			addCriterion("rule_code is null");
			return (Criteria) this;
		}

		public Criteria andRuleCodeIsNotNull() {
			addCriterion("rule_code is not null");
			return (Criteria) this;
		}

		public Criteria andRuleCodeEqualTo(String value) {
			addCriterion("rule_code =", value, "ruleCode");
			return (Criteria) this;
		}

		public Criteria andRuleCodeNotEqualTo(String value) {
			addCriterion("rule_code <>", value, "ruleCode");
			return (Criteria) this;
		}

		public Criteria andRuleCodeGreaterThan(String value) {
			addCriterion("rule_code >", value, "ruleCode");
			return (Criteria) this;
		}

		public Criteria andRuleCodeGreaterThanOrEqualTo(String value) {
			addCriterion("rule_code >=", value, "ruleCode");
			return (Criteria) this;
		}

		public Criteria andRuleCodeLessThan(String value) {
			addCriterion("rule_code <", value, "ruleCode");
			return (Criteria) this;
		}

		public Criteria andRuleCodeLessThanOrEqualTo(String value) {
			addCriterion("rule_code <=", value, "ruleCode");
			return (Criteria) this;
		}

		public Criteria andRuleCodeLike(String value) {
			addCriterion("rule_code like", value, "ruleCode");
			return (Criteria) this;
		}

		public Criteria andRuleCodeNotLike(String value) {
			addCriterion("rule_code not like", value, "ruleCode");
			return (Criteria) this;
		}

		public Criteria andRuleCodeIn(List<String> values) {
			addCriterion("rule_code in", values, "ruleCode");
			return (Criteria) this;
		}

		public Criteria andRuleCodeNotIn(List<String> values) {
			addCriterion("rule_code not in", values, "ruleCode");
			return (Criteria) this;
		}

		public Criteria andRuleCodeBetween(String value1, String value2) {
			addCriterion("rule_code between", value1, value2, "ruleCode");
			return (Criteria) this;
		}

		public Criteria andRuleCodeNotBetween(String value1, String value2) {
			addCriterion("rule_code not between", value1, value2, "ruleCode");
			return (Criteria) this;
		}

		public Criteria andRuleNameIsNull() {
			addCriterion("rule_name is null");
			return (Criteria) this;
		}

		public Criteria andRuleNameIsNotNull() {
			addCriterion("rule_name is not null");
			return (Criteria) this;
		}

		public Criteria andRuleNameEqualTo(String value) {
			addCriterion("rule_name =", value, "ruleName");
			return (Criteria) this;
		}

		public Criteria andRuleNameNotEqualTo(String value) {
			addCriterion("rule_name <>", value, "ruleName");
			return (Criteria) this;
		}

		public Criteria andRuleNameGreaterThan(String value) {
			addCriterion("rule_name >", value, "ruleName");
			return (Criteria) this;
		}

		public Criteria andRuleNameGreaterThanOrEqualTo(String value) {
			addCriterion("rule_name >=", value, "ruleName");
			return (Criteria) this;
		}

		public Criteria andRuleNameLessThan(String value) {
			addCriterion("rule_name <", value, "ruleName");
			return (Criteria) this;
		}

		public Criteria andRuleNameLessThanOrEqualTo(String value) {
			addCriterion("rule_name <=", value, "ruleName");
			return (Criteria) this;
		}

		public Criteria andRuleNameLike(String value) {
			addCriterion("rule_name like", value, "ruleName");
			return (Criteria) this;
		}

		public Criteria andRuleNameNotLike(String value) {
			addCriterion("rule_name not like", value, "ruleName");
			return (Criteria) this;
		}

		public Criteria andRuleNameIn(List<String> values) {
			addCriterion("rule_name in", values, "ruleName");
			return (Criteria) this;
		}

		public Criteria andRuleNameNotIn(List<String> values) {
			addCriterion("rule_name not in", values, "ruleName");
			return (Criteria) this;
		}

		public Criteria andRuleNameBetween(String value1, String value2) {
			addCriterion("rule_name between", value1, value2, "ruleName");
			return (Criteria) this;
		}

		public Criteria andRuleNameNotBetween(String value1, String value2) {
			addCriterion("rule_name not between", value1, value2, "ruleName");
			return (Criteria) this;
		}

		public Criteria andMaxRetryTimesIsNull() {
			addCriterion("max_retry_times is null");
			return (Criteria) this;
		}

		public Criteria andMaxRetryTimesIsNotNull() {
			addCriterion("max_retry_times is not null");
			return (Criteria) this;
		}

		public Criteria andMaxRetryTimesEqualTo(Short value) {
			addCriterion("max_retry_times =", value, "maxRetryTimes");
			return (Criteria) this;
		}

		public Criteria andMaxRetryTimesNotEqualTo(Short value) {
			addCriterion("max_retry_times <>", value, "maxRetryTimes");
			return (Criteria) this;
		}

		public Criteria andMaxRetryTimesGreaterThan(Short value) {
			addCriterion("max_retry_times >", value, "maxRetryTimes");
			return (Criteria) this;
		}

		public Criteria andMaxRetryTimesGreaterThanOrEqualTo(Short value) {
			addCriterion("max_retry_times >=", value, "maxRetryTimes");
			return (Criteria) this;
		}

		public Criteria andMaxRetryTimesLessThan(Short value) {
			addCriterion("max_retry_times <", value, "maxRetryTimes");
			return (Criteria) this;
		}

		public Criteria andMaxRetryTimesLessThanOrEqualTo(Short value) {
			addCriterion("max_retry_times <=", value, "maxRetryTimes");
			return (Criteria) this;
		}

		public Criteria andMaxRetryTimesIn(List<Short> values) {
			addCriterion("max_retry_times in", values, "maxRetryTimes");
			return (Criteria) this;
		}

		public Criteria andMaxRetryTimesNotIn(List<Short> values) {
			addCriterion("max_retry_times not in", values, "maxRetryTimes");
			return (Criteria) this;
		}

		public Criteria andMaxRetryTimesBetween(Short value1, Short value2) {
			addCriterion("max_retry_times between", value1, value2, "maxRetryTimes");
			return (Criteria) this;
		}

		public Criteria andMaxRetryTimesNotBetween(Short value1, Short value2) {
			addCriterion("max_retry_times not between", value1, value2, "maxRetryTimes");
			return (Criteria) this;
		}

		public Criteria andRetryDelayIsNull() {
			addCriterion("retry_delay is null");
			return (Criteria) this;
		}

		public Criteria andRetryDelayIsNotNull() {
			addCriterion("retry_delay is not null");
			return (Criteria) this;
		}

		public Criteria andRetryDelayEqualTo(Short value) {
			addCriterion("retry_delay =", value, "retryDelay");
			return (Criteria) this;
		}

		public Criteria andRetryDelayNotEqualTo(Short value) {
			addCriterion("retry_delay <>", value, "retryDelay");
			return (Criteria) this;
		}

		public Criteria andRetryDelayGreaterThan(Short value) {
			addCriterion("retry_delay >", value, "retryDelay");
			return (Criteria) this;
		}

		public Criteria andRetryDelayGreaterThanOrEqualTo(Short value) {
			addCriterion("retry_delay >=", value, "retryDelay");
			return (Criteria) this;
		}

		public Criteria andRetryDelayLessThan(Short value) {
			addCriterion("retry_delay <", value, "retryDelay");
			return (Criteria) this;
		}

		public Criteria andRetryDelayLessThanOrEqualTo(Short value) {
			addCriterion("retry_delay <=", value, "retryDelay");
			return (Criteria) this;
		}

		public Criteria andRetryDelayIn(List<Short> values) {
			addCriterion("retry_delay in", values, "retryDelay");
			return (Criteria) this;
		}

		public Criteria andRetryDelayNotIn(List<Short> values) {
			addCriterion("retry_delay not in", values, "retryDelay");
			return (Criteria) this;
		}

		public Criteria andRetryDelayBetween(Short value1, Short value2) {
			addCriterion("retry_delay between", value1, value2, "retryDelay");
			return (Criteria) this;
		}

		public Criteria andRetryDelayNotBetween(Short value1, Short value2) {
			addCriterion("retry_delay not between", value1, value2, "retryDelay");
			return (Criteria) this;
		}

		public Criteria andHttpMethodIsNull() {
			addCriterion("http_method is null");
			return (Criteria) this;
		}

		public Criteria andHttpMethodIsNotNull() {
			addCriterion("http_method is not null");
			return (Criteria) this;
		}

		public Criteria andHttpMethodEqualTo(String value) {
			addCriterion("http_method =", value, "httpMethod");
			return (Criteria) this;
		}

		public Criteria andHttpMethodNotEqualTo(String value) {
			addCriterion("http_method <>", value, "httpMethod");
			return (Criteria) this;
		}

		public Criteria andHttpMethodGreaterThan(String value) {
			addCriterion("http_method >", value, "httpMethod");
			return (Criteria) this;
		}

		public Criteria andHttpMethodGreaterThanOrEqualTo(String value) {
			addCriterion("http_method >=", value, "httpMethod");
			return (Criteria) this;
		}

		public Criteria andHttpMethodLessThan(String value) {
			addCriterion("http_method <", value, "httpMethod");
			return (Criteria) this;
		}

		public Criteria andHttpMethodLessThanOrEqualTo(String value) {
			addCriterion("http_method <=", value, "httpMethod");
			return (Criteria) this;
		}

		public Criteria andHttpMethodLike(String value) {
			addCriterion("http_method like", value, "httpMethod");
			return (Criteria) this;
		}

		public Criteria andHttpMethodNotLike(String value) {
			addCriterion("http_method not like", value, "httpMethod");
			return (Criteria) this;
		}

		public Criteria andHttpMethodIn(List<String> values) {
			addCriterion("http_method in", values, "httpMethod");
			return (Criteria) this;
		}

		public Criteria andHttpMethodNotIn(List<String> values) {
			addCriterion("http_method not in", values, "httpMethod");
			return (Criteria) this;
		}

		public Criteria andHttpMethodBetween(String value1, String value2) {
			addCriterion("http_method between", value1, value2, "httpMethod");
			return (Criteria) this;
		}

		public Criteria andHttpMethodNotBetween(String value1, String value2) {
			addCriterion("http_method not between", value1, value2, "httpMethod");
			return (Criteria) this;
		}

		public Criteria andHandlerIsNull() {
			addCriterion("handler is null");
			return (Criteria) this;
		}

		public Criteria andHandlerIsNotNull() {
			addCriterion("handler is not null");
			return (Criteria) this;
		}

		public Criteria andHandlerEqualTo(String value) {
			addCriterion("handler =", value, "handler");
			return (Criteria) this;
		}

		public Criteria andHandlerNotEqualTo(String value) {
			addCriterion("handler <>", value, "handler");
			return (Criteria) this;
		}

		public Criteria andHandlerGreaterThan(String value) {
			addCriterion("handler >", value, "handler");
			return (Criteria) this;
		}

		public Criteria andHandlerGreaterThanOrEqualTo(String value) {
			addCriterion("handler >=", value, "handler");
			return (Criteria) this;
		}

		public Criteria andHandlerLessThan(String value) {
			addCriterion("handler <", value, "handler");
			return (Criteria) this;
		}

		public Criteria andHandlerLessThanOrEqualTo(String value) {
			addCriterion("handler <=", value, "handler");
			return (Criteria) this;
		}

		public Criteria andHandlerLike(String value) {
			addCriterion("handler like", value, "handler");
			return (Criteria) this;
		}

		public Criteria andHandlerNotLike(String value) {
			addCriterion("handler not like", value, "handler");
			return (Criteria) this;
		}

		public Criteria andHandlerIn(List<String> values) {
			addCriterion("handler in", values, "handler");
			return (Criteria) this;
		}

		public Criteria andHandlerNotIn(List<String> values) {
			addCriterion("handler not in", values, "handler");
			return (Criteria) this;
		}

		public Criteria andHandlerBetween(String value1, String value2) {
			addCriterion("handler between", value1, value2, "handler");
			return (Criteria) this;
		}

		public Criteria andHandlerNotBetween(String value1, String value2) {
			addCriterion("handler not between", value1, value2, "handler");
			return (Criteria) this;
		}

		public Criteria andHandlerCharSetIsNull() {
			addCriterion("handler_char_set is null");
			return (Criteria) this;
		}

		public Criteria andHandlerCharSetIsNotNull() {
			addCriterion("handler_char_set is not null");
			return (Criteria) this;
		}

		public Criteria andHandlerCharSetEqualTo(String value) {
			addCriterion("handler_char_set =", value, "handlerCharSet");
			return (Criteria) this;
		}

		public Criteria andHandlerCharSetNotEqualTo(String value) {
			addCriterion("handler_char_set <>", value, "handlerCharSet");
			return (Criteria) this;
		}

		public Criteria andHandlerCharSetGreaterThan(String value) {
			addCriterion("handler_char_set >", value, "handlerCharSet");
			return (Criteria) this;
		}

		public Criteria andHandlerCharSetGreaterThanOrEqualTo(String value) {
			addCriterion("handler_char_set >=", value, "handlerCharSet");
			return (Criteria) this;
		}

		public Criteria andHandlerCharSetLessThan(String value) {
			addCriterion("handler_char_set <", value, "handlerCharSet");
			return (Criteria) this;
		}

		public Criteria andHandlerCharSetLessThanOrEqualTo(String value) {
			addCriterion("handler_char_set <=", value, "handlerCharSet");
			return (Criteria) this;
		}

		public Criteria andHandlerCharSetLike(String value) {
			addCriterion("handler_char_set like", value, "handlerCharSet");
			return (Criteria) this;
		}

		public Criteria andHandlerCharSetNotLike(String value) {
			addCriterion("handler_char_set not like", value, "handlerCharSet");
			return (Criteria) this;
		}

		public Criteria andHandlerCharSetIn(List<String> values) {
			addCriterion("handler_char_set in", values, "handlerCharSet");
			return (Criteria) this;
		}

		public Criteria andHandlerCharSetNotIn(List<String> values) {
			addCriterion("handler_char_set not in", values, "handlerCharSet");
			return (Criteria) this;
		}

		public Criteria andHandlerCharSetBetween(String value1, String value2) {
			addCriterion("handler_char_set between", value1, value2, "handlerCharSet");
			return (Criteria) this;
		}

		public Criteria andHandlerCharSetNotBetween(String value1, String value2) {
			addCriterion("handler_char_set not between", value1, value2, "handlerCharSet");
			return (Criteria) this;
		}

		public Criteria andHandlerParamsIsNull() {
			addCriterion("handler_params is null");
			return (Criteria) this;
		}

		public Criteria andHandlerParamsIsNotNull() {
			addCriterion("handler_params is not null");
			return (Criteria) this;
		}

		public Criteria andHandlerParamsEqualTo(String value) {
			addCriterion("handler_params =", value, "handlerParams");
			return (Criteria) this;
		}

		public Criteria andHandlerParamsNotEqualTo(String value) {
			addCriterion("handler_params <>", value, "handlerParams");
			return (Criteria) this;
		}

		public Criteria andHandlerParamsGreaterThan(String value) {
			addCriterion("handler_params >", value, "handlerParams");
			return (Criteria) this;
		}

		public Criteria andHandlerParamsGreaterThanOrEqualTo(String value) {
			addCriterion("handler_params >=", value, "handlerParams");
			return (Criteria) this;
		}

		public Criteria andHandlerParamsLessThan(String value) {
			addCriterion("handler_params <", value, "handlerParams");
			return (Criteria) this;
		}

		public Criteria andHandlerParamsLessThanOrEqualTo(String value) {
			addCriterion("handler_params <=", value, "handlerParams");
			return (Criteria) this;
		}

		public Criteria andHandlerParamsLike(String value) {
			addCriterion("handler_params like", value, "handlerParams");
			return (Criteria) this;
		}

		public Criteria andHandlerParamsNotLike(String value) {
			addCriterion("handler_params not like", value, "handlerParams");
			return (Criteria) this;
		}

		public Criteria andHandlerParamsIn(List<String> values) {
			addCriterion("handler_params in", values, "handlerParams");
			return (Criteria) this;
		}

		public Criteria andHandlerParamsNotIn(List<String> values) {
			addCriterion("handler_params not in", values, "handlerParams");
			return (Criteria) this;
		}

		public Criteria andHandlerParamsBetween(String value1, String value2) {
			addCriterion("handler_params between", value1, value2, "handlerParams");
			return (Criteria) this;
		}

		public Criteria andHandlerParamsNotBetween(String value1, String value2) {
			addCriterion("handler_params not between", value1, value2, "handlerParams");
			return (Criteria) this;
		}

		public Criteria andDescIsNull() {
			addCriterion("desc is null");
			return (Criteria) this;
		}

		public Criteria andDescIsNotNull() {
			addCriterion("desc is not null");
			return (Criteria) this;
		}

		public Criteria andDescEqualTo(String value) {
			addCriterion("desc =", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescNotEqualTo(String value) {
			addCriterion("desc <>", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescGreaterThan(String value) {
			addCriterion("desc >", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescGreaterThanOrEqualTo(String value) {
			addCriterion("desc >=", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescLessThan(String value) {
			addCriterion("desc <", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescLessThanOrEqualTo(String value) {
			addCriterion("desc <=", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescLike(String value) {
			addCriterion("desc like", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescNotLike(String value) {
			addCriterion("desc not like", value, "desc");
			return (Criteria) this;
		}

		public Criteria andDescIn(List<String> values) {
			addCriterion("desc in", values, "desc");
			return (Criteria) this;
		}

		public Criteria andDescNotIn(List<String> values) {
			addCriterion("desc not in", values, "desc");
			return (Criteria) this;
		}

		public Criteria andDescBetween(String value1, String value2) {
			addCriterion("desc between", value1, value2, "desc");
			return (Criteria) this;
		}

		public Criteria andDescNotBetween(String value1, String value2) {
			addCriterion("desc not between", value1, value2, "desc");
			return (Criteria) this;
		}

		public Criteria andBizCodeIsNull() {
			addCriterion("biz_code is null");
			return (Criteria) this;
		}

		public Criteria andBizCodeIsNotNull() {
			addCriterion("biz_code is not null");
			return (Criteria) this;
		}

		public Criteria andBizCodeEqualTo(String value) {
			addCriterion("biz_code =", value, "bizCode");
			return (Criteria) this;
		}

		public Criteria andBizCodeNotEqualTo(String value) {
			addCriterion("biz_code <>", value, "bizCode");
			return (Criteria) this;
		}

		public Criteria andBizCodeGreaterThan(String value) {
			addCriterion("biz_code >", value, "bizCode");
			return (Criteria) this;
		}

		public Criteria andBizCodeGreaterThanOrEqualTo(String value) {
			addCriterion("biz_code >=", value, "bizCode");
			return (Criteria) this;
		}

		public Criteria andBizCodeLessThan(String value) {
			addCriterion("biz_code <", value, "bizCode");
			return (Criteria) this;
		}

		public Criteria andBizCodeLessThanOrEqualTo(String value) {
			addCriterion("biz_code <=", value, "bizCode");
			return (Criteria) this;
		}

		public Criteria andBizCodeLike(String value) {
			addCriterion("biz_code like", value, "bizCode");
			return (Criteria) this;
		}

		public Criteria andBizCodeNotLike(String value) {
			addCriterion("biz_code not like", value, "bizCode");
			return (Criteria) this;
		}

		public Criteria andBizCodeIn(List<String> values) {
			addCriterion("biz_code in", values, "bizCode");
			return (Criteria) this;
		}

		public Criteria andBizCodeNotIn(List<String> values) {
			addCriterion("biz_code not in", values, "bizCode");
			return (Criteria) this;
		}

		public Criteria andBizCodeBetween(String value1, String value2) {
			addCriterion("biz_code between", value1, value2, "bizCode");
			return (Criteria) this;
		}

		public Criteria andBizCodeNotBetween(String value1, String value2) {
			addCriterion("biz_code not between", value1, value2, "bizCode");
			return (Criteria) this;
		}

		public Criteria andResponseCodeIsNull() {
			addCriterion("response_code is null");
			return (Criteria) this;
		}

		public Criteria andResponseCodeIsNotNull() {
			addCriterion("response_code is not null");
			return (Criteria) this;
		}

		public Criteria andResponseCodeEqualTo(String value) {
			addCriterion("response_code =", value, "responseCode");
			return (Criteria) this;
		}

		public Criteria andResponseCodeNotEqualTo(String value) {
			addCriterion("response_code <>", value, "responseCode");
			return (Criteria) this;
		}

		public Criteria andResponseCodeGreaterThan(String value) {
			addCriterion("response_code >", value, "responseCode");
			return (Criteria) this;
		}

		public Criteria andResponseCodeGreaterThanOrEqualTo(String value) {
			addCriterion("response_code >=", value, "responseCode");
			return (Criteria) this;
		}

		public Criteria andResponseCodeLessThan(String value) {
			addCriterion("response_code <", value, "responseCode");
			return (Criteria) this;
		}

		public Criteria andResponseCodeLessThanOrEqualTo(String value) {
			addCriterion("response_code <=", value, "responseCode");
			return (Criteria) this;
		}

		public Criteria andResponseCodeLike(String value) {
			addCriterion("response_code like", value, "responseCode");
			return (Criteria) this;
		}

		public Criteria andResponseCodeNotLike(String value) {
			addCriterion("response_code not like", value, "responseCode");
			return (Criteria) this;
		}

		public Criteria andResponseCodeIn(List<String> values) {
			addCriterion("response_code in", values, "responseCode");
			return (Criteria) this;
		}

		public Criteria andResponseCodeNotIn(List<String> values) {
			addCriterion("response_code not in", values, "responseCode");
			return (Criteria) this;
		}

		public Criteria andResponseCodeBetween(String value1, String value2) {
			addCriterion("response_code between", value1, value2, "responseCode");
			return (Criteria) this;
		}

		public Criteria andResponseCodeNotBetween(String value1, String value2) {
			addCriterion("response_code not between", value1, value2, "responseCode");
			return (Criteria) this;
		}

		public Criteria andComputerRoomIsNull() {
			addCriterion("computer_room is null");
			return (Criteria) this;
		}

		public Criteria andComputerRoomIsNotNull() {
			addCriterion("computer_room is not null");
			return (Criteria) this;
		}

		public Criteria andComputerRoomEqualTo(String value) {
			addCriterion("computer_room =", value, "computerRoom");
			return (Criteria) this;
		}

		public Criteria andComputerRoomNotEqualTo(String value) {
			addCriterion("computer_room <>", value, "computerRoom");
			return (Criteria) this;
		}

		public Criteria andComputerRoomGreaterThan(String value) {
			addCriterion("computer_room >", value, "computerRoom");
			return (Criteria) this;
		}

		public Criteria andComputerRoomGreaterThanOrEqualTo(String value) {
			addCriterion("computer_room >=", value, "computerRoom");
			return (Criteria) this;
		}

		public Criteria andComputerRoomLessThan(String value) {
			addCriterion("computer_room <", value, "computerRoom");
			return (Criteria) this;
		}

		public Criteria andComputerRoomLessThanOrEqualTo(String value) {
			addCriterion("computer_room <=", value, "computerRoom");
			return (Criteria) this;
		}

		public Criteria andComputerRoomLike(String value) {
			addCriterion("computer_room like", value, "computerRoom");
			return (Criteria) this;
		}

		public Criteria andComputerRoomNotLike(String value) {
			addCriterion("computer_room not like", value, "computerRoom");
			return (Criteria) this;
		}

		public Criteria andComputerRoomIn(List<String> values) {
			addCriterion("computer_room in", values, "computerRoom");
			return (Criteria) this;
		}

		public Criteria andComputerRoomNotIn(List<String> values) {
			addCriterion("computer_room not in", values, "computerRoom");
			return (Criteria) this;
		}

		public Criteria andComputerRoomBetween(String value1, String value2) {
			addCriterion("computer_room between", value1, value2, "computerRoom");
			return (Criteria) this;
		}

		public Criteria andComputerRoomNotBetween(String value1, String value2) {
			addCriterion("computer_room not between", value1, value2, "computerRoom");
			return (Criteria) this;
		}

		public Criteria andIoIsNull() {
			addCriterion("io is null");
			return (Criteria) this;
		}

		public Criteria andIoIsNotNull() {
			addCriterion("io is not null");
			return (Criteria) this;
		}

		public Criteria andIoEqualTo(String value) {
			addCriterion("io =", value, "io");
			return (Criteria) this;
		}

		public Criteria andIoNotEqualTo(String value) {
			addCriterion("io <>", value, "io");
			return (Criteria) this;
		}

		public Criteria andIoGreaterThan(String value) {
			addCriterion("io >", value, "io");
			return (Criteria) this;
		}

		public Criteria andIoGreaterThanOrEqualTo(String value) {
			addCriterion("io >=", value, "io");
			return (Criteria) this;
		}

		public Criteria andIoLessThan(String value) {
			addCriterion("io <", value, "io");
			return (Criteria) this;
		}

		public Criteria andIoLessThanOrEqualTo(String value) {
			addCriterion("io <=", value, "io");
			return (Criteria) this;
		}

		public Criteria andIoLike(String value) {
			addCriterion("io like", value, "io");
			return (Criteria) this;
		}

		public Criteria andIoNotLike(String value) {
			addCriterion("io not like", value, "io");
			return (Criteria) this;
		}

		public Criteria andIoIn(List<String> values) {
			addCriterion("io in", values, "io");
			return (Criteria) this;
		}

		public Criteria andIoNotIn(List<String> values) {
			addCriterion("io not in", values, "io");
			return (Criteria) this;
		}

		public Criteria andIoBetween(String value1, String value2) {
			addCriterion("io between", value1, value2, "io");
			return (Criteria) this;
		}

		public Criteria andIoNotBetween(String value1, String value2) {
			addCriterion("io not between", value1, value2, "io");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("version is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("version is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("version =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("version <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("version >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("version >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("version <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("version <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<Integer> values) {
			addCriterion("version in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<Integer> values) {
			addCriterion("version not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("version between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("version not between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated do_not_delete_during_merge Wed May 17 11:39:00 CST 2023
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}

	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	public static class Criterion {

		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			}
			else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}

	}

}