# 日志模式
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
# 暴露监控端点
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        ## yml文件中存在特殊字符，必须用单引号包含，否则启动报错
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
  # trace 配置（100%）
  tracing:
    sampling:
      probability: 1.0
server:
  # 开启优雅停机，默认IMMEDIATE是立即关机，graceful是等待处理完请求再关机
  shutdown: graceful