# https://hub.docker.com/_/mysql
# 指定 Docker Compose 文件格式的版本
version: '3.9'
# 定义服务部分，可以包含一个或多个服务配置
services:
  # 服务的名称，这里是 MySQL 服务
  mysql:
    # MySQL 镜像的版本，这里是 8.0.15
    image: mysql:8.0.15
    # 指定容器的名称为 mysql8
    container_name: mysql8
    # 定义容器退出后的重启策略，这里是始终重启，除非明确停止容器
    # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    restart: unless-stopped
    # 定义数据卷挂载路径，将本机目录映射到容器目录
    # 数据卷挂载路径设置,将本机目录映射到容器目录
    volumes:
      - "./my.cnf:/etc/mysql/my.cnf"
      - "/usr/local/docker-volumes/mysql/data:/var/lib/mysql"
      - "/usr/local/docker-volumes/mysql/mysql-files:/var/lib/mysql-files"
    # 设置环境变量，包括时区、字符集、root 用户密码和初始化的数据库名称。
    # 设置环境变量,相当于docker run命令中的-e参数
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: root         # 设置root用户密码
      MYSQL_DATABASE: demo              # 初始化的数据库名称
    # 启用特权模式，可以在容器内执行特权操作
    privileged: true
    # 将容器内的用户设置为 root 用户。
    user: root
    #  映射端口，将容器内的 MySQL 3306 端口映射到主机的 3308 端口
    ports:
      - "3308:3306"
