### 创建秒杀活动
POST http://localhost:8080/seckill/activity/create
Content-Type: application/json

{
  "activityName": "活动名称",
  "activityDesc": "活动描述",
  "startTime": "2022-12-20 09:30:00",
  "endTime": "2022-12-20 10:30:00"
}

### 秒杀活动添加商品
POST http://localhost:8080/seckill/activity/goods/create
Content-Type: application/json

{
  "seckillActivityId": 1,
  "goodsList": [
    {
    "goodsId": 1,
    "seckillPrice": 5,
    "seckillCount": 20,
    "seckillLimit": 1,
    "seckillSort": 1
    },
    {
      "goodsId": 2,
      "seckillPrice": 6,
      "seckillCount": 10,
      "seckillLimit": 1,
      "seckillSort": 2
    }
  ]
}