package com.tomato.mybatis.generator.mapper;

import com.tomato.mybatis.generator.entity.NoticeRule;
import com.tomato.mybatis.generator.entity.NoticeRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoticeRuleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	long countByExample(NoticeRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	int deleteByExample(NoticeRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	int insert(NoticeRule row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	int insertSelective(NoticeRule row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	List<NoticeRule> selectByExample(NoticeRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	NoticeRule selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	int updateByExampleSelective(@Param("row") NoticeRule row, @Param("example") NoticeRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	int updateByExample(@Param("row") NoticeRule row, @Param("example") NoticeRuleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	int updateByPrimaryKeySelective(NoticeRule row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the
	 * database table t_notice_rule
	 *
	 * @mbg.generated Wed May 17 11:39:00 CST 2023
	 */
	int updateByPrimaryKey(NoticeRule row);

}