### 查询
POST http://localhost:9998/order/query/merchant
Content-Type: application/json

{
  "merchantOrderNo": "admin",
  "merchantNo": "123456",
  "hmac": "123456"
}

### 订单号查询
POST http://localhost:9998/order/query/orderNo
Content-Type: application/json

{
  "orderNo": "admin",
  "merchantNo": "123456",
  "hmac": "123456"
}