spring:
  profiles:
    active: dev,druid,mybatis

  jackson:
    mapper:
      default-view-inclusion: true
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-ignored-properties: false
      fail-on-unknown-properties: false
      accept-single-value-as-array: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  output:
    ansi:
      #DETECT：会检查终端是否支持ANSI，是的话就采用彩色输出（推荐项）
      enabled: detect
  session:
    store-type: none

logging:
  config: classpath:log4j2.xml

server:
  port: 8080
  maxHttpHeaderSize: 10485760
  servlet:
    context-path: /api

jwt:
  secretkey: rJ1lN9tP1rR2iX7hX1iO1wF9mW8aS2mAmV0JdNgw4tNtQvvEwapWZWRbsvS5b4r7g46C
  # 24 hours
  validtiy: 24h


