# 端口号
server:
  port: 9998

spring:
  profiles:
    active: @profiles.active@
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  application:
    # 应用名称，用于注册到注册中心，pom.xml中的artifactId
    name: @artifactId@
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        # 注册中心地址,dns解析 127.0.0.1  tomato-nacos
        server-addr: ${NACOS_HOST:tomato-nacos}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
    openfeign:
      client:
        config:
          default: # 项目全局feign配置
            loggerLevel: full
  config:
    import:
      # 从nacos中获取配置
      - optional:nacos:application-@profiles.active@.yml
      # 从nacos中获取配置
      - optional:nacos:${spring.application.name}-@profiles.active@.yml
      - optional:nacos:application-common.yml
logging:
  level:
    com.tomato.merchant.api: debug # 这里是openfeign client 所在的包路径

mybatis:
  type-aliases-package: com.tomato.order.infrastructure.dataobject
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#management:
#  prometheus:
#    metrics:
#      export:
#        pushgateway:
#          enabled: true
#          base-url: http://tomato-prometheus-pushgateway:9091
#          job: tomato-module-order-start2