spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tomato-mysql:3306/tomato_seckill?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true
    username: tomato
    password: tomato
  data:
    redis:
      host: ${REDIS_HOST:tomato-redis}